Modded_weapons = {
    --melée
    "WEAPON_HANDCUFFS",--
    "WEAPON_GARBAGEBAG",--
    --projectiles
    "weapon_bzgas",--
    "weapon_fireextinguisher",--
    "weapon_fertilizercan",--
    "weapon_ball",--
    "weapon_snowball",--
    "weapon_acidpackage",--
    "weapon_flare",--
    "WEAPON_BIRD_CRAP",--
    "WEAPON_METALDETECTOR",--
    --pistolets
    "weapon_stungun",--
    "weapon_stungun_mp",--
    "weapon_tranquilizer",--
    --lourde
    "weapon_railgun",--
    "weapon_emplauncher",--
    "weapon_railgunxm3",--
    "WEAPON_GRENADELAUNCHER_SMOKE",--
    "weapon_stinger",--
    "weapon_vehicle_rocket",--

    --autre
    "weapon_digiscanner",--
    "weapon_briefcase",--
    "weapon_briefcase_02",--
    "GADGET_NIGHTVISION",--
    "GADGET_PARACHUTE",--

    --????
    "remotesniper",
    "weapon_passenger_rocket",
    "weapon_airstrike_rocket",
    "weapon_barbed_wire",
    "weapon_drowning",
    "weapon_drowning_in_vehicle",
    "weapon_bleeding",
    "weapon_electric_fence",
    "weapon_explosion",
    "weapon_fall",
    "weapon_exhaustion",
    "weapon_hit_by_water_cannon",
    "weapon_rammed_by_car",
    "weapon_run_over_by_car",
    "weapon_heli_crash",
    "weapon_fire",
}
Weapons = {

    --melée
    "weapon_unarmed",
    "weapon_knife",--
    "weapon_nightstick",--
    "weapon_hammer",--
    "weapon_bat",--
    "weapon_crowbar",--
    "weapon_golfclub",--
    "weapon_bottle",--
    "weapon_dagger",--
    "weapon_hatchet",--
    "weapon_machete",--
    "weapon_flashlight",--
    "weapon_switchblade",--
    "weapon_battleaxe",--
    "weapon_poolcue",--
    "weapon_wrench",--
    "weapon_stone_hatchet",--
    "weapon_candycane",--
    --unarmed
    "weapon_knuckle",--
    "WEAPON_COUGAR",--
    --projectiles
    "weapon_grenade",--
    "weapon_stickybomb",--
    "weapon_proxmine",--
    "weapon_pipebomb",--
    "weapon_smokegrenade",--
    "weapon_molotov",--
    "weapon_petrolcan",--
    "weapon_hazardcan",--
    --pistolets
    "weapon_pistol",--
    "weapon_pistol_mk2",--
    "weapon_combatpistol",--
    "weapon_pistol50",--
    "weapon_snspistol",--
    "weapon_snspistol_mk2",--
    "weapon_heavypistol",--
    "weapon_vintagepistol",--
    "weapon_ceramicpistol",--
    "weapon_marksmanpistol",--
    "weapon_revolver",--
    "weapon_revolver_mk2",--
    "weapon_doubleaction",--
    "weapon_navyrevolver",--
    "weapon_gadgetpistol",--
    "weapon_pistolxm3",--
    "weapon_appistol",--
    "weapon_flaregun",--
    "weapon_raypistol",--
    --mitrailleuses
    "weapon_microsmg",--
    "weapon_machinepistol",--
    "weapon_minismg",--
    "weapon_smg",--
    "weapon_smg_mk2",--
    "weapon_assaultsmg",--
    "weapon_combatpdw",--
    "weapon_mg",--
    "weapon_combatmg",--
    "weapon_combatmg_mk2",--
    "weapon_gusenberg",--
    "weapon_raycarbine",--
    --fusils
    "weapon_assaultrifle",--
    "weapon_assaultrifle_mk2",--
    "weapon_carbinerifle",--
    "weapon_carbinerifle_mk2",--
    "weapon_advancedrifle",--
    "weapon_specialcarbine",--
    "weapon_specialcarbine_mk2",--
    "weapon_bullpuprifle",--
    "weapon_bullpuprifle_mk2",--
    "weapon_compactrifle",--
    "weapon_militaryrifle",--
    "weapon_heavyrifle",--
    "weapon_tacticalrifle",--
    --fusil de précision
    "weapon_sniperrifle",--
    "weapon_heavysniper",--
    "weapon_heavysniper_mk2",--
    "weapon_marksmanrifle",--
    "weapon_marksmanrifle_mk2",--
    "weapon_precisionrifle",--
    --fusils à pompe
    "weapon_pumpshotgun",--
    "weapon_pumpshotgun_mk2",--
    "weapon_sawnoffshotgun",--
    "weapon_bullpupshotgun",--
    "weapon_assaultshotgun",--
    "weapon_musket",--
    "weapon_heavyshotgun",--
    "weapon_dbshotgun",--
    "weapon_autoshotgun",--
    "weapon_combatshotgun",--
    --armes lourdes
    "weapon_grenadelauncher",--
    "weapon_rpg",--
    "weapon_minigun",--
    "weapon_firework",--
    "weapon_hominglauncher",--
    "weapon_compactlauncher",--
    "weapon_rayminigun",--
}
